name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    strategy:
      matrix:
        java: [17-ubuntu, 21-ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: Install git on container
        run: |
          apt update
          apt install -y git
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: gradle/wrapper-validation-action@v2
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew check build publishToMavenLocal --stacktrace --warning-mode=fail -Porg.gradle.parallel.threads=4
      - name: Capture build artifacts
        if: ${{ matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-
          path: build/libs/
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        with:
          name: Maven Local
          path: /root/.m2/repository/com/github/salandora
  check_resources:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: chmod +x ./gradlew
      - run: ./gradlew generateResources --stacktrace --warning-mode=fail
      - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi